version: '3.8'

services:
  back:
    build:
      context: ./back
      dockerfile: _docker/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - back_data:/var/www/html
      - storage_uploads:/var/www/html/storage/app/public
    depends_on:
      - mysql
    networks:
      - laravel_vue_store
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_vue_store
      DB_USERNAME: root
      DB_PASSWORD: laravel_vue_store_pass

  front:
    build:
      context: ./front
      dockerfile: _docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - front_data:/app
    depends_on:
      - back
    networks:
      - laravel_vue_store

  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: laravel_vue_store_pass
      MYSQL_DATABASE: laravel_vue_store
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_vue_store

volumes:
  back_data:
  storage_uploads:
  front_data:
  mysql_data:

networks:
  laravel_vue_store:
    driver: bridge
