version: '3.8'

services:
  back:
    build:
      context: ./back
      dockerfile: _docker/Dockerfile
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    volumes:
      - ./back:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel_vue_store


  front:
    build:
      context: ./front
      dockerfile: _docker/Dockerfile
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    volumes:
      - ./front:/app
    depends_on:
      - back
    networks:
      - laravel_vue_store


  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_vue_store

volumes:
  mysql_data:
  front:
  back:

networks:
  laravel_vue_store:
    driver: bridge
